---
abstract: "Detect perl's global phase on older perls."
author:
  - 'Graham Knop <haarg@haarg.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-GlobalPhase
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008
resources:
  homepage: http://github.com/haarg/Devel-GlobalPhase
  repository: git://github.com/haarg/Devel-GlobalPhase.git
version: 0.002000
